name: Ubuntu (from source)

on:
  workflow_dispatch:

jobs:
  build-and-push-ubuntu-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - root-version: v6-26-00
            cpp-standard: 17
            ubuntu-version: 20.04

    env:
      IMAGE_NAME_WITH_TAG: ghcr.io/${{ github.repository_owner }}/root:${{ matrix.root-version }}-ubuntu${{ matrix.ubuntu-version }}-cpp${{ matrix.cpp-standard }}-from-source

    steps:
      - name: Print Image name with tag(s)
        run: |
          echo "Image name with tag: ${{ env.IMAGE_NAME_WITH_TAG }}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_WRITE_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: ubuntu_from_source/
          pull: true
          push: true
          build-args: |
            ROOT_VERSION=${{ matrix.root-version }}
            CMAKE_CXX_STANDARD=${{ matrix.cpp-standard }}
            UBUNTU_VERSION=${{ matrix.ubuntu-version }}
          tags: ${{ env.IMAGE_NAME_WITH_TAG }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
