name: Build and Publish Fedora Image

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Trigger Build and Publish All Images"]
    types:
      - completed

jobs:
  build-and-push-fedora-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - root-version: 6.24.06
            fedora-version: 35
          - root-version: 6.22.08
            fedora-version: 34
          - root-version: 6.22.06
            fedora-version: 33

    env:
      IMAGE_NAME_WITH_TAG: ghcr.io/${{ github.repository_owner }}/root:${{ matrix.root-version }}-fedora${{ matrix.fedora-version }}

    steps:
      - name: Print Image name with tag(s)
        run: |
          echo "Image name with tag: ${{ env.IMAGE_NAME_WITH_TAG }}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_WRITE_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: fedora/
          pull: true
          push: true
          build-args: |
            FEDORA_VERSION=${{ matrix.fedora-version }}
          tags: ${{ env.IMAGE_NAME_WITH_TAG }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Test ROOT Version
        run: |
          docker run ${{ env.IMAGE_NAME_WITH_TAG }} root-config --version
