name: Build and Publish Ubuntu Image (from binaries)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Publish All Images"]
    types:
      - completed

jobs:
  build-and-push-ubuntu-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        root-version:
          [
            6.26.00,
            6.24.06,
            6.24.02,
            6.24.00,
            6.22.08,
            6.22.06,
            6.22.02,
            6.22.00,
            6.20.08,
          ]
        ubuntu-version: [20.04]

    env:
      IMAGE_NAME_WITH_TAG: ghcr.io/${{ github.repository_owner }}/root:${{ matrix.root-version }}-ubuntu${{ matrix.ubuntu-version }}

    steps:
      - name: Print Image name with tag(s)
        run: |
          echo "Image name with tag: ${{ env.IMAGE_NAME_WITH_TAG }}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_WRITE_TOKEN }}

      #  - name: Log in to Docker Hub
      #    uses: docker/login-action@v1
      #    with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: ubuntu/
          pull: true
          push: true
          build-args: |
            ROOT_BIN=root_v${{ matrix.root-version }}.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
            UBUNTU_VERSION=${{ matrix.ubuntu-version }}
          tags: ${{ env.IMAGE_NAME_WITH_TAG }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Add 'latest' tag
        if: ${{ matrix.root-version == '6.26.00' }}
        run: |
          docker image tag ${{ env.IMAGE_NAME_WITH_TAG }} ghcr.io/${{ github.repository_owner }}/root:latest
          docker push
