name: Fedora

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Trigger Build and Publish All Images"]
    types:
      - completed

jobs:
  build-and-push-fedora-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME_WITH_TAG: ghcr.io/${{ github.repository_owner }}/root:latest-fedora

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_WRITE_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: fedora/
          pull: true
          push: false
          tags: ${{ env.IMAGE_NAME_WITH_TAG }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Test ROOT Version
        run: |
          docker run ${{ env.IMAGE_NAME_WITH_TAG }} root-config --version | sed -r 's/\//./g'
          export ROOT_VERSION=$(docker run ${{ env.IMAGE_NAME_WITH_TAG }} root-config --version | sed -r 's/\//./g')
          echo "ROOT_VERSION=${{ ROOT_VERSION }}"
          echo "ROOT_VERSION=${{ ROOT_VERSION }}" >> $GITHUB_ENV

      - name: Add additional tag to image and push it
        run: |
          docker tag ${{ env.IMAGE_NAME_WITH_TAG }}: ghcr.io/${{ github.repository_owner }}/root:${{ env.ROOT_VERSION }}-fedora
          docker push ${{ env.IMAGE_NAME_WITH_TAG }}
